# Generated by Django 6.0 on 2026-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="peso_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Peso del producto en kg",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
