# Generated by Django 6.0 on 2026-01-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buy_order",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
