# Generated by Django 6.0 on 2026-01-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_buy_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de pago"),
                    ("pagada", "Pagada"),
                    ("fallida", "Fallida"),
                    ("cancelada", "Cancelada"),
                    (
                        "pendiente_confirmacion",
                        "Pendiente confirmación (transferencia)",
                    ),
                    ("contra_entrega", "Contra entrega"),
                    ("en_preparacion", "En preparación"),
                    ("en_despacho", "En despacho"),
                    ("entregada", "Entregada"),
                ],
                default="pendiente",
                max_length=30,
            ),
        ),
    ]
